### ISSUE TITLE
Unrecognized argument. The container `ReservoirSimulationTimeSeries` does not take an argument `base_ensembles`.

### ISSUE THREAD

**Issue by runemorten** [equinor/webviz-subsurface#140]
Running command "webviz build" fails with:

Unrecognized argument. The container `ReservoirSimulationTimeSeries` does not take an argument `base_ensembles`.

**Comment by HansKallekleiv** [comment]
Hi @runemorten ,
Yes this container has been rewritten and the arguments has changed.
Since we are still early in the development, such changes are hard to avoid.

It is now only necessary to provide the `ensembles` argument. 
Difference calculations between ensembles is done and selected interactively in the app.

You can find two examples here: https://github.com/equinor/webviz-subsurface-testdata/blob/master/webviz_examples/raw_data.yaml#L49

**Comment by anders-kiaer** [comment]
Talked to @runemorten - problem solved.
