### ISSUE TITLE
Eclipse runs that crash are given 0 values in time series

### ISSUE THREAD

**Issue by asnyv** [equinor/webviz-subsurface#237]
Eclipse runs that crash are given 0 values in time series from the timestep they crash. Misleading, and also creates unrealistic delta profiles. Better to drop realization completely if it doesn't finish?

Example fan chart:
![image](https://user-images.githubusercontent.com/47146384/75024491-c7f9fc80-5499-11ea-9148-322a07cb6fc4.png)

Example delta:
![image](https://user-images.githubusercontent.com/47146384/75024913-8b7ad080-549a-11ea-8530-2ff3d0f9be4b.png)

**Comment by berland** [comment]
Check this: 

https://equinor.github.io/fmu-ensemble/usage.html#filtering-realizations

Filtering on 'OK' probably makes sense here, because that is a sure indicator of failure.

I don't think fmu-ensemble should automatically drop realizations that does not go all the way to the "end", it could be intentional to have different simulation endpoints.  

But, fmu.ensemble does not zero-pad summary vectors forward in time in the get_smry() functions. But perhaps through some other statistical functions? If so, that might be a bug in fmu.ensemble.

**Comment by asnyv** [comment]
Looked a bit more into this @berland. Seems like fmu.ensemble stops at the crash date if `time_index` is defaulted, while if it is e.g. 'monthly' it will interpolate, giving flat values for some vectors (typically cumulatives, some pressures ++) , and zeroes or NaNs for other vectors.

**Comment by berland** [comment]
Would resolution of this https://github.com/equinor/fmu-ensemble/issues/94 help?
