### ISSUE TITLE
Master failing with Dash 1.11

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/webviz-subsurface#317]
Suddenly the [`master` branch is failing](https://github.com/equinor/webviz-subsurface/actions?query=branch%3Amaster), due to timeout on one of the subsurface surface tests.

Investigate what has changed, and if it is needed to increase the timeout.

One way of 🔍 investigation could be to start with comparing versions used of upstream packages (use the printed CI lists of installed software from a successfull run, and a failed run, and compare).

```
    def test_surface_selector(dash_duo):
    
        app = dash.Dash(__name__)
        app.config.suppress_callback_exceptions = True
        realizations = pd.read_csv("tests/data/realizations.csv")
        s = SurfaceSelector(app, surface_context, realizations)
    
        app.layout = html.Div(children=[s.layout, html.Pre(id="pre", children="ok")])
    
        @app.callback(Output("pre", "children"), [Input(s.storage_id, "children")])
        def _test(data):
            return json.dumps(json.loads(data))
    
        dash_duo.start_server(app)
    
>       dash_duo.wait_for_contains_text("#pre", json.dumps(return_value), timeout=4)
```

**Comment by HansKallekleiv** [comment]
This is due to changes in the Dash callback pipeline introduced in Dash 1.11.
https://github.com/plotly/dash/pull/1103

There are multiple issues going on here, so far identified:
- dash.callback_context.triggered now does NOT reflect any initial values - This causes issues with initial rendering in some plugins (e.g. https://github.com/equinor/webviz-subsurface/blob/fafa5d6742a07e91198f322c7ff1d7cc6b161c4e/webviz_subsurface/plugins/_reservoir_simulation_timeseries_onebyone.py#L354)

- Changes to callback validation exposed some "wrong" prop usage in callbacks. More precisely several plugins are using dcc.Store(children) as prop which is not valid(should use dcc.Store(data)). 

Awaiting further testing until https://github.com/plotly/dash/issues/1200 is fixed.
