### ISSUE TITLE
Eclipse UDQs

### ISSUE THREAD

**Issue by havarhal** [equinor/webviz-subsurface#321]
When loading webviz, warnings related to Eclipse user define quantities(UDQs) appear. Suggest to turn off the check for descriptions of vectors starting with 'CU',' FU','GU','RU','SU','WU', 'AU' and 'BU'.

**Comment by asnyv** [comment]
Good point @havarhal 👍 Would it be useful to add a description like "VECTOR (UDQ)" to these vectors? To make it possible to search for UDQs?

**Comment by havarhal** [comment]
You mean like a user defined description?

**Comment by asnyv** [comment]
Was thinking just a general. More like a "UDQ" tag behind the vector name. Have a feeling that most users will not bother to make user defined ones even if that was an option?

**Comment by havarhal** [comment]
I agree, but adding UDQ as a general description was not a bad idea :)

**Comment by anders-kiaer** [comment]
>Have a feeling that most users will not bother to make user defined ones even if that was an option?

Many users might not do that effort, but perhaps we should add the possibility. I know that some assets want to make time series more available to non-reservoir-engineers, and giving the user the possibility to provide some custom descriptions of vectors could be useful (especially for e.g. UDQ vectors which might be quite difficult to interpret for persons not setting up the simulation model).

This "standard customization" can be added to e.g. let the user provide metadata in the form of `(time, vector, some text)` in order to annotate given plots (where then e.g. a vertical line with some text appears at the given time. Could be useful for curves where the user wants to tell a "story" (e.g. tracer curves, annotate when the tracer component was injected, explain some sharp changes in rate curves etc.).

Could be as simple as an optional `yaml` input file to the `ReservoirTimeSeriesPlugin`, where vector descriptions are merged with the standard provided dictionary.

**Comment by asnyv** [comment]
Think you should then split the UDQ description and plot annotations in separate structures. Too many options in the same file are confusing, especially when it comes to what is optional, and what is required. 

The UDQ description is also something which is "global" in the app (at least for an ensemble, can probably also assume it is for an app). Many plugins have simulation vectors, like `ReservoirSimulationTimeSeries`, `ReservoirSimulationTimeSeriesOneByOne`, `ParameterResponseCorrelation`, future plugin for simulated inplace and recovery, and probably several AHM plugins and etc in the future. Shouldn't have to define this file for each plugin.
Annotations are on the other hand more for specific plots in my opinion (though they could of course be stored "globally").

**Comment by asnyv** [comment]
Divided this into 2 parts, to get the most urgent (remove the warnings) in for next komodo version. 

Status:
- [x] Remove warnings for UDQs: Solved in #332 
- [ ] User defined UDQ descriptions

**Comment by jorgenherje** [comment]
Will be resolved by PR in #940 

Note: This PR makes it possible to create user defined vector definitions for all types of vectors - not only UDQ's

**Comment by jorgenherje** [comment]
Closed by https://github.com/equinor/webviz-subsurface/pull/940
