### ISSUE TITLE
Improved selection menu Simulation time series plug-in

### ISSUE THREAD

**Issue by howardovic** [equinor/webviz-subsurface#555]
It is cumbersome to find the right vector to plot in the "Simulation time series" plugin. 
I propose implementing the selection menu from ResInsight: 
![image](https://user-images.githubusercontent.com/54617976/106271380-baafcb00-622f-11eb-8f96-49ef16da77fe.png)

**Comment by asnyv** [comment]
Hi @howardovic!

We are working on an improved vector selector as we speak. It is not planned to be exactly as the ResInsight one, but instead a bit more compact with grouping and suggestions on the fly. 
One of the reasons is that quite a few users prefer the current searchable variant over the ResInsight selector which requires a lot of clicks to navigate.
Another reason is that the simulation time series plugin also supports non-Eclipse data (through csv input), so the classification is a bit looser than in ResInsight. 

Added the initial sketch below, will probably be entirely how it ends up, but something along this road is our current plan. Do you think this could work for you? So the plan is basically a searchable box like today, but with more structured suggestions. 
If you have any inputs, now is the time to come up with them :) 

![image](https://user-images.githubusercontent.com/47146384/106273868-a1108280-6233-11eb-91c1-d9bdccc808fe.png)

**Comment by asnyv** [comment]
Also relates to #469

**Comment by howardovic** [comment]
Hi.

Looks nice!

One suggestion though. Once the user has selected the vector and made
plott(s), make it easy to switch source. F.eks, present the other
wells/regions in a clickable list. Also jumping between source/iterations
should be smooth.
[image: image.png]
[image: image.png]



 Allow the user to choose choose between, rather than presenting items in a
drop-down menu,

**Comment by asnyv** [comment]
@howardovic we will still keep an ensemble selector as today I think, since you usually want to plot the same data(sets). 
The source/ensemble selector option suggested here is mainly for various calculations (e.g. a vector calculator, deltas and etc), so in the regular viewer, the ensemble/source will be detached from the vector selection. 

@rubenthoms knows the details better than me, but as the current prototype works, you can navigate inside an entry. E.g if you have your cursor in the OP_1 area, the other wells will show up in the suggestion list/dropdown to switch. We also consider to add up and down arrows to click through the options, e.g. for wells in WBHP. 

And: I'm sorry, but I don't understand what you mean by choose betweem, rather than presenting items in a drop-down menu?
Also, if you tried to attached pictures, they are not shown unfortunately.

**Comment by howardovic** [comment]
Pictures

![image](https://user-images.githubusercontent.com/54617976/106284284-4da63080-6243-11eb-9e00-c57691fff507.png)

![image](https://user-images.githubusercontent.com/54617976/106284299-539c1180-6243-11eb-969d-3bacb51cd881.png)

**Comment by ManInFez** [comment]
https://github.com/equinor/webviz-ert/commit/4df32848fa9ec74bf6aed2ea23f851e7e06799cc This could maybe be used as inspiriation?

**Comment by anders-kiaer** [comment]
A first version of this selector is now merged to `master` and can be viewed here: https://webviz-subsurface-example.azurewebsites.net/simulation-time-series :tada: 

Improvement suggestions on the new component can be created in seperate/new issues like this one https://github.com/equinor/webviz-core-components/issues/149 :slightly_smiling_face:
