### ISSUE TITLE
Data loading of eclipse summary vectors

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface#631]
Problem:
I often have to reload webviz when changing ensembles or plugins. It takes a lot of time and is a bit frustrating when working.

Proposed solution:
The first time an ensemble is loaded, the summary data is stored in a file on the scratch disk (parquet-file?). The next time Webviz is loading the same ensemble it can just read the file which should be much faster.

**Comment by anders-kiaer** [comment]
Based on what @sigurdp has done through factory, and since we also have the "portable build option" (which is basically "store to data and make it quick afterwards"), I think this is done? Feel free to reopen if not.

We could prioritize/consider https://github.com/equinor/webviz-config/issues/236 - in order to improve user communication further on this feature.
