### ISSUE TITLE
Single realization option in `WellCompletion`

### ISSUE THREAD

**Issue by lindjoha** [equinor/webviz-subsurface#900]
The `WellCompletion` plugin is only set up to use an ensemble data set. But it would be useful to also have an option to select single realizations. I think this cannot be done front end since the data set would become to large. Backend it is straight forward to do it, the problem is what to do with the portable option. Webviz store is currently saving the finished data set, but that can't be done for every realisation (that would become too much data). So the webviz-store would have to be moved to the input data. In which case the plugin would be slower when run portable since putting together the data takes some time.

**Comment by anders-kiaer** [comment]
As discussed with @lindjoha, the main question is how this is best handled on the data side.

It would be nice to investigate if we, instead of storing aggregated data on ensemble level, could store `WellCompletion` data on realization level and from there quickly aggregate on demand.

This enables:
- `WellCompletion` will become compatible wilth global realization filter (when/if that becomes a reality).
- `WellCompletion` is SUMO-ready 🎉
